project:
  type: manuscript

bibliography: references.bib
csl: csl/apa.csl

manuscript:
  article: paper.qmd

format:
  html:
    other-formats: false
  docx: default
  pdf: default

execute:
  freeze: true
